### PR TITLE
Phase2

### PR DESCRIPTION
**Pull request by kateinoigakukun**
- [x] Parse `name` section for backtrace
- [x] `memory` command which dump memory space
- [x] Interceptor
  - [x] Breakpoint
  - [ ] ~~Watch global variable~~
- [x] Parse DWARF info

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
Not sure if you've seen this, but might be relevant: https://erikmcclure.com/blog/debugging-through-webassembly-is-impossible/

**Comment by kateinoigakukun** [comment]
@MaxDesiatov  Thank you for your info! As I read the article, it means "Debugging through WebAssembly is impossible because inNative is AOT compiler".
I noticed this problem while extending wasmtime to debug Swift binary. This is why I implemented this debugger as an interpreter instead of JIT or AOT compiler.

wasminspect is an interpreter of wasm and has a memory space controlled by wasminspect instead of OS to ignore the base address.

Thank you again and if you notice any issue, please tell me!

**Comment by MaxDesiatov** [comment]
@kateinoigakukun thanks for the clarification! It feels like I'm going to get much more free time myself in a few weeks and planning to increase my contributions as soon as possible. 

Do you think it would be hard to write at least some useful code for this debugger in Swift? Just more interested in making more of this code available to the Swift community and my knowledge of Rust is pretty basic. As far as I understand there are a few Rust dependencies, but I'm wondering if some of those have analogues in Swift or maybe could expose C bindings?

**Comment by kateinoigakukun** [comment]
@MaxDesiatov Thanks for your interest of contribution to this project! The reasons why I implemented this debugger in rust are,
- There are some valuable library to parse wasm binary
- Just for my Rust practice

IMO, it's not so much hard to make this in Swift but I wanted to make this as soon as possible, I decided to use rust libraries. But reusing the rust library from Swift using C binding is difficult 😅.

**Comment by kateinoigakukun** [comment]
@MaxDesiatov It would be great step toward getting swiftwasm project to be merged in upstream  if you fix [test cases](https://github.com/swiftwasm/swift/issues/29). 🙇

**Pull request merged**
